DROP TABLE IF EXISTS knowledge_nodes;

CREATE TABLE IF NOT EXISTS knowledge_nodes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT,
    name         VARCHAR(128) NOT NULL,
    parent_id    BIGINT,
    remark       VARCHAR(100),
    deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    creator      VARCHAR(64) DEFAULT '',
    create_time  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater      VARCHAR(64) DEFAULT '',
    update_time  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- 自引用外键；删除父节点时把子节点的 parent_id 置 NULL（避免测试清理时卡住）
ALTER TABLE knowledge_nodes
    ADD CONSTRAINT fk_kn_parent
        FOREIGN KEY (parent_id) REFERENCES knowledge_nodes (id)
            ON DELETE SET NULL;